import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';

const mainStyles = css`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  h1 {
    font-weight: 400;
  }
`;
const spanStyles = css`
  margin: 1rem;
  font-size: 24px;
  text-align: center;
`;
const imageStyles = css`
  margin: 1rem 0;
  border: 2px solid black;
  border-radius: 8px;
  box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Final Project</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main css={mainStyles}>
        <h1>Welcome to Splitify</h1>
        <span css={spanStyles}>Take a sneak peek how the app works</span>
        <div>
          {/* <Image
            css={imageStyles}
            src="/images/eventpic1.png"
            alt=" Picture of event page"
            height="572px"
            width="379,5px"
          />
          <Image
            css={imageStyles}
            src="/images/eventpic2.png"
            alt="Picture of Expense List"
            height="711px"
            width="375px"
          /> */}
          <Image
            css={imageStyles}
            src="/images/eventpic3.png"
            alt="Picture of Result calculation"
            height="586px"
            width="382px"
          />
        </div>
        <span css={spanStyles}>
          <a href="./register">Create an Account</a> to use our Service
        </span>
      </main>
    </>
  );
}
