import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';

const mainStyles = css`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;

  h1 {
    font-weight: 400;
  }
`;
const spanStyles = css`
  margin: 1rem;
  font-size: 24px;
  text-align: center;
`;
const imageStyles = css`
  margin: 1rem 0;
  border: 2px solid black;
  border-radius: 8px;
  box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
`;
const exampleImageContainer = css`
  display: flex;
  @media only screen and (max-width: 800px) {
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }
`;
const viewMoreButtonStyles = css`
  padding: 8px;

  border: 2px solid black;
  border-radius: 8px;
  font-size: 20px;
  color: white;

  background: linear-gradient(to right top, #043159, #10528e, #2a689f);
  cursor: pointer;
`;

export default function Home() {
  const [viewMoreImages, setViewMoreImages] = useState(false);

  return (
    <>
      <Head>
        <title>Splitify - Final Project Upleveled</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main css={mainStyles}>
        <h1>Welcome to Splitify</h1>
        <p css={spanStyles}>
          Splitify allows you to split up expenses fast and easy.
        </p>

        <span css={spanStyles}>Take a sneak peek how the app works</span>
        <div>
          <Image
            css={imageStyles}
            src="/images/eventpic3.png"
            alt="Picture of Result calculation"
            height="586px"
            width="382px"
          />
        </div>
        {viewMoreImages ? (
          <>
            <div css={exampleImageContainer}>
              <Image
                css={imageStyles}
                src="/images/eventpic4.png"
                alt="Picture of an example expense list"
                height="700px"
                width="382px"
              />
              <Image
                css={imageStyles}
                src="/images/eventpic1.png"
                alt="Picture of Example Event"
                height={586}
                width={382}
              />
            </div>
            <button
              css={viewMoreButtonStyles}
              onClick={() => {
                setViewMoreImages(false);
              }}
            >
              Close
            </button>
          </>
        ) : (
          <button
            css={viewMoreButtonStyles}
            onClick={() => {
              setViewMoreImages(true);
            }}
          >
            See more
          </button>
        )}
        <span css={spanStyles}>
          <a href="./register">Create an Account</a> to use our Service
        </span>
      </main>
    </>
  );
}
